/**
 * The Counting House - Mock Event Data
 * Based on seed.sql for development before Supabase connection
 */

import type { Event, EventType, QuarterType, Expense, FiscalYear } from '@/types/database';

// ============================================
// FISCAL YEAR
// ============================================

export const mockFiscalYear: FiscalYear = {
  id: 'fy-2026-0001',
  year: 2026,
  created_at: '2026-01-01T00:00:00Z',
};

// ============================================
// MOCK EVENTS (Based on seed.sql)
// ============================================

const now = new Date().toISOString();

export const mockEvents: Event[] = [
  // ============================================
  // EXECUTIVE EVENTS (12 events)
  // ============================================
  {
    id: 'evt-exec-001',
    name: 'ASHA Annual Meeting',
    event_type: 'executive',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-01-15',
    date_end: '2026-01-17',
    location: 'Washington, DC',
    budget_amount: 16500,
    expansion_goal: 25,
    net_new_goal: 10,
    approach_notes: 'Focus on C-suite networking opportunities',
    marketing_notes: 'Booth #234, premium location',
    sales_notes: 'Pre-scheduled meetings with 5 target accounts',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-002',
    name: 'Healthtac East',
    event_type: 'executive',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-02-03',
    date_end: '2026-02-05',
    location: 'Amelia Island, FL',
    budget_amount: 30500,
    expansion_goal: 40,
    net_new_goal: 15,
    approach_notes: 'Executive retreat format, casual networking',
    marketing_notes: null,
    sales_notes: 'Golf tournament sponsor',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-003',
    name: 'NIC Spring Conference',
    event_type: 'executive',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-03-04',
    date_end: '2026-03-06',
    location: 'San Diego, CA',
    budget_amount: 65000,
    expansion_goal: 100,
    net_new_goal: 35,
    approach_notes: 'Major industry event - full activation',
    marketing_notes: 'Large booth with demo stations',
    sales_notes: 'Hosting executive dinner Tuesday night',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-004',
    name: 'Senior Living 100 Conference',
    event_type: 'executive',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-03-18',
    date_end: '2026-03-20',
    location: 'Palm Beach, FL',
    budget_amount: 40000,
    expansion_goal: 50,
    net_new_goal: 20,
    approach_notes: 'Top 100 operators - invitation only',
    marketing_notes: null,
    sales_notes: 'Speaking slot confirmed',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-005',
    name: 'NIC Growth Conference',
    event_type: 'executive',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-04-22',
    date_end: '2026-04-24',
    location: 'Atlanta, GA',
    budget_amount: 8700,
    expansion_goal: 20,
    net_new_goal: 8,
    approach_notes: 'Smaller NIC event, focused on growth stage companies',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-006',
    name: "Alzheimer's Association - Vision Gala",
    event_type: 'executive',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-05-10',
    date_end: '2026-05-10',
    location: 'Chicago, IL',
    budget_amount: 5000,
    expansion_goal: 10,
    net_new_goal: 5,
    approach_notes: 'Industry awareness and relationship building',
    marketing_notes: null,
    sales_notes: 'Table sponsor',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-007',
    name: 'SLIF Spring',
    event_type: 'executive',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-05-14',
    date_end: '2026-05-16',
    location: 'Austin, TX',
    budget_amount: 35000,
    expansion_goal: 45,
    net_new_goal: 18,
    approach_notes: 'Senior Living Innovation Forum - tech focused',
    marketing_notes: 'Innovation showcase booth',
    sales_notes: 'Demo sessions scheduled',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-008',
    name: 'ASHA Mid-Year Meeting',
    event_type: 'executive',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-06-08',
    date_end: '2026-06-10',
    location: 'Nashville, TN',
    budget_amount: 8000,
    expansion_goal: 15,
    net_new_goal: 6,
    approach_notes: 'Mid-year member meeting, smaller attendance',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-009',
    name: 'NIC Fall Conference',
    event_type: 'executive',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-09-22',
    date_end: '2026-09-24',
    location: 'Chicago, IL',
    budget_amount: 50000,
    expansion_goal: 80,
    net_new_goal: 30,
    approach_notes: 'Largest NIC event of the year',
    marketing_notes: 'Premium booth location secured',
    sales_notes: 'Executive dinner and 1:1 meetings',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-010',
    name: 'Marsh Risk Summit',
    event_type: 'executive',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-10-15',
    date_end: '2026-10-16',
    location: 'New York, NY',
    budget_amount: 7500,
    expansion_goal: 12,
    net_new_goal: 5,
    approach_notes: 'Risk management focused, insurance partners',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-011',
    name: 'SLIF Fall',
    event_type: 'executive',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-11-03',
    date_end: '2026-11-05',
    location: 'Scottsdale, AZ',
    budget_amount: 35000,
    expansion_goal: 40,
    net_new_goal: 15,
    approach_notes: 'Fall innovation forum',
    marketing_notes: 'Product launch opportunity',
    sales_notes: 'Year-end deal push',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-exec-012',
    name: 'Argentum Leadership Summit',
    event_type: 'executive',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-11-17',
    date_end: '2026-11-19',
    location: 'Phoenix, AZ',
    budget_amount: 38000,
    expansion_goal: 50,
    net_new_goal: 20,
    approach_notes: 'Year-end executive gathering',
    marketing_notes: 'End of year brand reinforcement',
    sales_notes: 'Pipeline close event',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },

  // ============================================
  // NATIONAL EVENTS (19 events)
  // ============================================
  {
    id: 'evt-natl-001',
    name: 'AgeTech',
    event_type: 'national',
    quarter: 'TBD',
    fiscal_year_id: 'fy-2026-0001',
    date_start: null,
    date_end: null,
    location: 'TBD',
    budget_amount: 25000,
    expansion_goal: 30,
    net_new_goal: 12,
    approach_notes: 'Technology-focused aging conference',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-002',
    name: 'AgeTech Workshops',
    event_type: 'national',
    quarter: 'TBD',
    fiscal_year_id: 'fy-2026-0001',
    date_start: null,
    date_end: null,
    location: 'Multiple locations',
    budget_amount: 48000,
    expansion_goal: 50,
    net_new_goal: 20,
    approach_notes: 'Hands-on workshop series',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-003',
    name: 'Interface West',
    event_type: 'national',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-01-28',
    date_end: '2026-01-29',
    location: 'Los Angeles, CA',
    budget_amount: 1700,
    expansion_goal: 8,
    net_new_goal: 3,
    approach_notes: 'Regional interface event',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-004',
    name: 'SHN Sales & Marketing Conference',
    event_type: 'national',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-02-10',
    date_end: '2026-02-12',
    location: 'Dallas, TX',
    budget_amount: 2200,
    expansion_goal: 12,
    net_new_goal: 5,
    approach_notes: 'Marketing team attendance',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-005',
    name: 'Argentum PPI',
    event_type: 'national',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-02-24',
    date_end: '2026-02-26',
    location: 'Washington, DC',
    budget_amount: 2500,
    expansion_goal: 10,
    net_new_goal: 4,
    approach_notes: 'Policy and advocacy focus',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-006',
    name: 'Future Care',
    event_type: 'national',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-03-10',
    date_end: '2026-03-11',
    location: 'Boston, MA',
    budget_amount: 800,
    expansion_goal: 5,
    net_new_goal: 2,
    approach_notes: 'Emerging trends conference',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-007',
    name: 'LeadingAge Leadership Summit',
    event_type: 'national',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-04-14',
    date_end: '2026-04-16',
    location: 'Denver, CO',
    budget_amount: 12500,
    expansion_goal: 25,
    net_new_goal: 10,
    approach_notes: 'Non-profit sector focus',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-008',
    name: 'LALS LifeLoop+SY Dinner',
    event_type: 'national',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-04-15',
    date_end: '2026-04-15',
    location: 'Denver, CO',
    budget_amount: 1500,
    expansion_goal: 8,
    net_new_goal: 3,
    approach_notes: 'Partner co-hosted dinner',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-009',
    name: 'Argentum Executive Conference',
    event_type: 'national',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-05-04',
    date_end: '2026-05-07',
    location: 'Orlando, FL',
    budget_amount: 80000,
    expansion_goal: 120,
    net_new_goal: 45,
    approach_notes: 'Largest Argentum event - full activation',
    marketing_notes: 'Major booth presence',
    sales_notes: 'Multiple hospitality events planned',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-010',
    name: 'Interface Midwest',
    event_type: 'national',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-06-16',
    date_end: '2026-06-17',
    location: 'Chicago, IL',
    budget_amount: 1500,
    expansion_goal: 8,
    net_new_goal: 3,
    approach_notes: 'Regional interface event',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-011',
    name: 'NARA Licensing Seminar',
    event_type: 'national',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-07-20',
    date_end: '2026-07-21',
    location: 'Las Vegas, NV',
    budget_amount: 1000,
    expansion_goal: 5,
    net_new_goal: 2,
    approach_notes: 'Regulatory and licensing focus',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-012',
    name: 'WIL Forum',
    event_type: 'national',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-08-11',
    date_end: '2026-08-13',
    location: 'San Francisco, CA',
    budget_amount: 5000,
    expansion_goal: 15,
    net_new_goal: 6,
    approach_notes: 'Women in Leadership forum',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-013',
    name: 'Value Based Care Workshop',
    event_type: 'national',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-08-25',
    date_end: '2026-08-26',
    location: 'Minneapolis, MN',
    budget_amount: 5000,
    expansion_goal: 12,
    net_new_goal: 5,
    approach_notes: 'Healthcare economics workshop',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-014',
    name: 'SMASH',
    event_type: 'national',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-10-05',
    date_end: '2026-10-07',
    location: 'San Diego, CA',
    budget_amount: 5000,
    expansion_goal: 15,
    net_new_goal: 6,
    approach_notes: 'Sales and marketing summit',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-015',
    name: 'AHCA/NCAL Convention',
    event_type: 'national',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-10-18',
    date_end: '2026-10-21',
    location: 'Nashville, TN',
    budget_amount: 18000,
    expansion_goal: 35,
    net_new_goal: 14,
    approach_notes: 'Skilled nursing and assisted living focus',
    marketing_notes: 'Standard booth',
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-016',
    name: 'LeadingAge Annual Meeting',
    event_type: 'national',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-11-08',
    date_end: '2026-11-11',
    location: 'Indianapolis, IN',
    budget_amount: 30000,
    expansion_goal: 50,
    net_new_goal: 20,
    approach_notes: 'Largest LeadingAge event',
    marketing_notes: 'Large booth with demos',
    sales_notes: 'Key target accounts attending',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-017',
    name: 'SHN BUILD/BRAIN Conference',
    event_type: 'national',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-12-01',
    date_end: '2026-12-03',
    location: 'Washington, DC',
    budget_amount: 15000,
    expansion_goal: 25,
    net_new_goal: 10,
    approach_notes: 'Development and operations focus',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-018',
    name: 'Interface Northeast',
    event_type: 'national',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-12-08',
    date_end: '2026-12-09',
    location: 'Boston, MA',
    budget_amount: 1200,
    expansion_goal: 6,
    net_new_goal: 2,
    approach_notes: 'Regional interface event',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-natl-019',
    name: 'OnAging',
    event_type: 'national',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-06-22',
    date_end: '2026-06-24',
    location: 'Seattle, WA',
    budget_amount: 10000,
    expansion_goal: 20,
    net_new_goal: 8,
    approach_notes: 'Aging services innovation',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },

  // ============================================
  // STATE EVENTS (13 events)
  // ============================================
  {
    id: 'evt-state-001',
    name: 'LeadingAge CA RISE',
    event_type: 'state',
    quarter: 'Q1',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-02-18',
    date_end: '2026-02-20',
    location: 'Sacramento, CA',
    budget_amount: 1200,
    expansion_goal: 6,
    net_new_goal: 2,
    approach_notes: 'California LeadingAge event',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-002',
    name: 'TALA Annual Conference',
    event_type: 'state',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-04-28',
    date_end: '2026-04-30',
    location: 'Austin, TX',
    budget_amount: 4000,
    expansion_goal: 15,
    net_new_goal: 6,
    approach_notes: 'Texas assisted living association',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-003',
    name: 'LeadingAge CA Annual',
    event_type: 'state',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-05-18',
    date_end: '2026-05-20',
    location: 'San Diego, CA',
    budget_amount: 1300,
    expansion_goal: 8,
    net_new_goal: 3,
    approach_notes: 'Annual California meeting',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-004',
    name: 'CALA Spring Conference',
    event_type: 'state',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-05-26',
    date_end: '2026-05-28',
    location: 'Monterey, CA',
    budget_amount: 11000,
    expansion_goal: 25,
    net_new_goal: 10,
    approach_notes: 'California assisted living - spring',
    marketing_notes: 'Booth presence',
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-005',
    name: 'GSLA Gala',
    event_type: 'state',
    quarter: 'Q2',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-06-05',
    date_end: '2026-06-05',
    location: 'Atlanta, GA',
    budget_amount: 300,
    expansion_goal: 5,
    net_new_goal: 2,
    approach_notes: 'Georgia senior living gala',
    marketing_notes: null,
    sales_notes: 'Table attendance',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-006',
    name: 'LifeSpan',
    event_type: 'state',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-07-14',
    date_end: '2026-07-16',
    location: 'Columbus, OH',
    budget_amount: 4000,
    expansion_goal: 12,
    net_new_goal: 5,
    approach_notes: 'Ohio aging services',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-007',
    name: 'LeadingAge Southeast',
    event_type: 'state',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-08-04',
    date_end: '2026-08-06',
    location: 'Charlotte, NC',
    budget_amount: 4600,
    expansion_goal: 15,
    net_new_goal: 6,
    approach_notes: 'Southeast regional LeadingAge',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-008',
    name: 'FSLA Conference',
    event_type: 'state',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-09-08',
    date_end: '2026-09-10',
    location: 'Orlando, FL',
    budget_amount: 8000,
    expansion_goal: 20,
    net_new_goal: 8,
    approach_notes: 'Florida senior living association',
    marketing_notes: 'Booth',
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-009',
    name: 'Interface SE',
    event_type: 'state',
    quarter: 'Q3',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-09-15',
    date_end: '2026-09-16',
    location: 'Atlanta, GA',
    budget_amount: 1200,
    expansion_goal: 6,
    net_new_goal: 2,
    approach_notes: 'Southeast interface event',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-010',
    name: 'GSLA Conference',
    event_type: 'state',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-10-27',
    date_end: '2026-10-29',
    location: 'Savannah, GA',
    budget_amount: 10000,
    expansion_goal: 22,
    net_new_goal: 9,
    approach_notes: 'Georgia senior living main conference',
    marketing_notes: 'Booth presence',
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-011',
    name: 'FSLA Advocacy Days',
    event_type: 'state',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-11-12',
    date_end: '2026-11-13',
    location: 'Tallahassee, FL',
    budget_amount: 500,
    expansion_goal: 3,
    net_new_goal: 1,
    approach_notes: 'Florida advocacy event',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-012',
    name: 'CALA Fall Conference',
    event_type: 'state',
    quarter: 'Q4',
    fiscal_year_id: 'fy-2026-0001',
    date_start: '2026-11-24',
    date_end: '2026-11-26',
    location: 'Palm Springs, CA',
    budget_amount: 10000,
    expansion_goal: 25,
    net_new_goal: 10,
    approach_notes: 'California assisted living - fall',
    marketing_notes: 'Booth presence',
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'evt-state-013',
    name: 'Regional/State Bucket',
    event_type: 'state',
    quarter: 'TBD',
    fiscal_year_id: 'fy-2026-0001',
    date_start: null,
    date_end: null,
    location: 'Various',
    budget_amount: 60000,
    expansion_goal: 50,
    net_new_goal: 20,
    approach_notes: 'Flexible budget for additional state events',
    marketing_notes: null,
    sales_notes: null,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },

  // ============================================
  // CUSTOMER EVENTS (1 event)
  // ============================================
  {
    id: 'evt-cust-001',
    name: 'Customer Events (General)',
    event_type: 'customer',
    quarter: 'TBD',
    fiscal_year_id: 'fy-2026-0001',
    date_start: null,
    date_end: null,
    location: 'Various',
    budget_amount: 150000,
    expansion_goal: 100,
    net_new_goal: 40,
    approach_notes: 'Customer-hosted events and activations',
    marketing_notes: 'Customized per event',
    sales_notes: 'Direct customer engagement',
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
];

// ============================================
// MOCK EXPENSES (Sample expenses for events)
// ============================================

export const mockExpenses: Expense[] = [
  // Expenses for NIC Spring Conference
  {
    id: 'exp-001',
    event_id: 'evt-exec-003',
    category_id: null,
    amount: 15000,
    expense_date: '2026-01-15',
    vendor: 'NIC Conference',
    memo: 'Booth registration and sponsorship',
    source_type: 'manual',
    source_reference: null,
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'exp-002',
    event_id: 'evt-exec-003',
    category_id: null,
    amount: 8500,
    expense_date: '2026-02-01',
    vendor: 'Marriott San Diego',
    memo: 'Hotel block deposit',
    source_type: 'brex',
    source_reference: 'brex-txn-001',
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'exp-003',
    event_id: 'evt-exec-003',
    category_id: null,
    amount: 3200,
    expense_date: '2026-02-15',
    vendor: 'Catering Plus',
    memo: 'Executive dinner catering deposit',
    source_type: 'pdf',
    source_reference: 'invoice-catering-001.pdf',
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  // Expenses for ASHA Annual Meeting
  {
    id: 'exp-004',
    event_id: 'evt-exec-001',
    category_id: null,
    amount: 5500,
    expense_date: '2025-12-01',
    vendor: 'ASHA',
    memo: 'Conference registration and booth',
    source_type: 'manual',
    source_reference: null,
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'exp-005',
    event_id: 'evt-exec-001',
    category_id: null,
    amount: 2800,
    expense_date: '2026-01-05',
    vendor: 'Delta Airlines',
    memo: 'Team flights to DC',
    source_type: 'brex',
    source_reference: 'brex-txn-002',
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  // Expenses for Argentum Executive Conference
  {
    id: 'exp-006',
    event_id: 'evt-natl-009',
    category_id: null,
    amount: 25000,
    expense_date: '2026-01-20',
    vendor: 'Argentum',
    memo: 'Premier sponsorship package',
    source_type: 'manual',
    source_reference: null,
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  {
    id: 'exp-007',
    event_id: 'evt-natl-009',
    category_id: null,
    amount: 12000,
    expense_date: '2026-02-10',
    vendor: 'Orlando Convention Center',
    memo: 'Suite rental for hospitality',
    source_type: 'pdf',
    source_reference: 'invoice-occ-001.pdf',
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  // Expenses for Healthtac East
  {
    id: 'exp-008',
    event_id: 'evt-exec-002',
    category_id: null,
    amount: 18000,
    expense_date: '2025-12-15',
    vendor: 'Healthtac',
    memo: 'Golf tournament sponsorship',
    source_type: 'manual',
    source_reference: null,
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  // Expenses for CALA Spring Conference
  {
    id: 'exp-009',
    event_id: 'evt-state-004',
    category_id: null,
    amount: 4500,
    expense_date: '2026-03-01',
    vendor: 'CALA',
    memo: 'Booth registration',
    source_type: 'manual',
    source_reference: null,
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
  // More diverse expenses
  {
    id: 'exp-010',
    event_id: 'evt-exec-009',
    category_id: null,
    amount: 18500,
    expense_date: '2026-07-01',
    vendor: 'NIC',
    memo: 'Fall conference premier booth',
    source_type: 'manual',
    source_reference: null,
    is_duplicate: false,
    created_at: now,
    updated_at: now,
    deleted_at: null,
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

/**
 * Get all events, optionally filtered
 */
export function getEvents(filters?: {
  event_type?: EventType;
  quarter?: QuarterType;
  fiscal_year_id?: string;
}): Event[] {
  let events = mockEvents.filter(e => !e.deleted_at);

  if (filters?.event_type) {
    events = events.filter(e => e.event_type === filters.event_type);
  }
  if (filters?.quarter) {
    events = events.filter(e => e.quarter === filters.quarter);
  }
  if (filters?.fiscal_year_id) {
    events = events.filter(e => e.fiscal_year_id === filters.fiscal_year_id);
  }

  return events;
}

/**
 * Get a single event by ID
 */
export function getEventById(id: string): Event | undefined {
  return mockEvents.find(e => e.id === id && !e.deleted_at);
}

/**
 * Get expenses for an event
 */
export function getExpensesByEventId(eventId: string): Expense[] {
  return mockExpenses.filter(e => e.event_id === eventId && !e.deleted_at);
}

/**
 * Calculate actual spent for an event
 */
export function getEventActualSpent(eventId: string): number {
  return getExpensesByEventId(eventId).reduce((sum, e) => sum + e.amount, 0);
}

/**
 * Get event with calculated totals
 */
export interface EventWithTotals extends Event {
  actual_spent: number;
  remaining: number;
  expense_count: number;
}

export function getEventWithTotals(event: Event): EventWithTotals {
  const expenses = getExpensesByEventId(event.id);
  const actual_spent = expenses.reduce((sum, e) => sum + e.amount, 0);

  return {
    ...event,
    actual_spent,
    remaining: event.budget_amount - actual_spent,
    expense_count: expenses.length,
  };
}

/**
 * Get all events with totals
 */
export function getEventsWithTotals(filters?: {
  event_type?: EventType;
  quarter?: QuarterType;
  fiscal_year_id?: string;
}): EventWithTotals[] {
  const events = getEvents(filters);
  return events.map(getEventWithTotals);
}

/**
 * Event type display labels
 */
export const eventTypeLabels: Record<EventType, string> = {
  executive: 'Executive',
  national: 'National',
  state: 'State',
  regional: 'Regional',
  customer: 'Customer',
};

/**
 * Quarter display labels
 */
export const quarterLabels: Record<QuarterType, string> = {
  Q1: 'Q1 (Jan-Mar)',
  Q2: 'Q2 (Apr-Jun)',
  Q3: 'Q3 (Jul-Sep)',
  Q4: 'Q4 (Oct-Dec)',
  TBD: 'TBD',
};
